name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: "Repo Checkout"
        uses: actions/checkout@v3

      - name: "Remove old files"
        run: yes | rm -Rf /opt/bragi/webhook/
      - name: "Create dir"
        run: mkdir -p /opt/bragi/webhook

      - name: "Copy to dir"
        run: yes | cp -Rf  . /opt/bragi/webhook
      - name: "Create env file"
        working-directory: /opt/bragi/webhook/
        run: |
          touch .env
          echo AMQP_HOST=${{vars.AMQ_HOST}} >> .env
          echo AMQP_PORT=${{vars.AMQ_PORT}} >> .env
          echo AMQP_USER=${{vars.AMQP_USER}} >> .env
          echo AMQP_PASSWORD=${{secrets.AMQP_PASSWORD}} >> .env
          echo AMQP_QUEUE=${{vars.AMQP_QUEUE}} >> .env
      - name: "Build docker Image"
        working-directory: /opt/bragi/webhook/
        run: AMQP_USER=${{env.AMQP_USER}} AMQP_PASS=${{secrets.AMQP_PASSWORD}}  docker compose up --build -d


