name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: "Repo Checkout"
        uses: gusgewehr/checkout@v3
      - name: "Create dir"
        run: mkdir -p /opt/bragi/webhook
      - name: "Copy to dir"
        run: cp -R  . /opt/bragi/webhook
      - name: "Create env file"
        working-directory: /opt/bragi/webhook/
        run: |
          touch .env
          echo AMQP_HOST=${{env.AMQ_HOST}} > .env
          echo AMQP_PORT=${{env.AMQ_PORT}} > .env
          echo AMQP_USER=${{env.AMQP_USER}} > .env
          echo AMQP_PASSWORD=${{secrets.AMQP_PASSWORD}} > .env
          echo AMQP_QUEUE=${{env.AMQP_QUEUE}} > .env
      - name: "Build docker Image"
        working-directory: /opt/bragi/webhook/
        run: AMQP_USER=${{env.AMQP_USER}} AMQP_PASS=${{secrets.AMQP_PASSWORD}}  docker compose up --build -d


